version: "3.9"

services:

  as:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ./docker-compose.env
    ports:
      - "8000:8000"
    extra_hosts:
      - "${DOCKER_COMPOSE_DEFAULT_NETWORK_GATEWAY_FQDN}:${DOCKER_COMPOSE_DEFAULT_NETWORK_GATEWAY}"
    volumes:
      - "./example/:/run/spid-django/example/"
      - "./src/:/run/spid-django/src/"

  spid-testenv2:
    image: italia/spid-testenv2:1.1.0
    ports:
      - "8088:8088"
    extra_hosts:
      - "${DOCKER_COMPOSE_DEFAULT_NETWORK_GATEWAY_FQDN}:${DOCKER_COMPOSE_DEFAULT_NETWORK_GATEWAY}"
    volumes:
      - "./example/configs/spid-testenv2/config.yaml:/app/conf/config.yaml:ro"
      - "./example/configs/spid-testenv2/users.json:/app/conf/users.json:ro"

  spid-saml-check:
    build:
      context: ./spid-saml-check/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    extra_hosts:
      - "${DOCKER_COMPOSE_DEFAULT_NETWORK_GATEWAY_FQDN}:${DOCKER_COMPOSE_DEFAULT_NETWORK_GATEWAY}"
    volumes:
      - "./example/configs/spid-saml-check/idp.json:/spid-saml-check/spid-validator/config/idp.json:ro"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${DOCKER_COMPOSE_DEFAULT_NETWORK_SUBNET}
          gateway: ${DOCKER_COMPOSE_DEFAULT_NETWORK_GATEWAY}
